name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Latest blog post workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@deshankoswatte"
          max_post_count: 5
          commit_message: Update README with the latest blog posts
          committer_username: deshankoswatte
          committer_email: dehami.deshan@gmail.com
          gh_token: ${{ secrets.GH_TOKEN }}